export const BACK = 'REACT_NATIVE_ROUTER_EX_BACK';
export const BACK_ACTION = 'BackAction'; // Internal NavigationExperimental action
export const MODAL = 'REACT_NATIVE_ROUTER_EX_MODAL';
export const MODAL_POP = 'REACT_NATIVE_ROUTER_EX_MODAL_POP';
export const NAVINIT = 'REACT_NATIVE_ROUTER_EX_NAVINIT';
export const POP = 'REACT_NATIVE_ROUTER_EX_POP';
export const POP_TO = 'REACT_NATIVE_ROUTER_EX_POP_TO';
export const PUSH = 'REACT_NATIVE_ROUTER_EX_PUSH';
export const SWITCH = 'REACT_NATIVE_ROUTER_EX_SWITCH';
